[WIP]Design database
yuto-ishida/chat-space pull request #1
Opened 2019-03-02 07:44 UTC by yuto-ishida

#　WHAT
ChatspaceのDB設計をする。

#　アプリケーションを作成するのに必須のため

2019-03-02 08:07 UTC, TOMARUMARU reviewed
usersとgroupsは中間テーブルを用いた多対多のアソシエーションになるので、調べて修正をお願いします

2019-03-03 03:59 UTC, kuroko918 reviewed
https://qiita.com/Kohei_Kishimoto0214/items/cb9a3d3da57708fb52c9
こちらのサイトでrailsの多対多についてまとめられているので、こちらも参考に修正お願いいたします。

2019-03-03 03:59 UTC, kuroko918 commented on README.md
> +|group_id|integer|null: false, foreign_key: true|
group_idは外部キーカラムになるので、groupsテーブルには設置できないです。
groupsテーブルはnameカラムを持つかと思います。

2019-03-03 03:59 UTC, kuroko918 commented on README.md
> +- has_many :users_group
中間テーブルの名前はusers_groupではなく、membersテーブルと設定されているので、has_many :membersですね。
また、group has_many :usersも必要ですね！

2019-03-03 03:59 UTC, kuroko918 commented on README.md
> +|user_id|integer|null: false, foreign_key: true|
こちらも同様に、user_idはusersテーブルが持つものではないです。
userテーブルはnameや、emailなどのカラムが必要かと思います。

2019-03-03 03:59 UTC, kuroko918 commented on README.md
> +- has_many :groups_user
中間テーブルの名前はusers_groupではなく、membersテーブルと設定されているので、has_many :membersですね。
また、group has_many :groupsも必要ですね！

2019-03-03 03:59 UTC, kuroko918 commented on README.md
> +## chatsテーブル
カリキュラムではmesssagesテーブルとなってしまっているので、そちらの方がカリキュラムを読み進めやすいかと思いますので、messsagesテーブルと命名しておいてください。

2019-03-03 03:59 UTC, kuroko918 commented on README.md
> +|chat_id|integer|null: false, foreign_key: true|
こちらも同様に、messsagesテーブルが自身の外部キーカラムを持つことはないので、消しておいてください。
また、messagesテーブルにはcommentカラムや、imageカラムが必要かと思います。

2019-03-03 03:59 UTC, kuroko918 commented on README.md
> +- has_many :users_group
こちらはhas_many :users_groupは必要ないですね。
message belongs_to :user、belongs_to :groupですね。
またそれに伴って、userとgroupの外部キーカラムもmessagesテーブルには必要かと思います。

2019-03-03 05:43 UTC, yuto-ishida commented
> usersとgroupsは中間テーブルを用いた対多のアソシエーションになるので、調べて修正をお願いします

修正いたしました。お手数おかけ致しますがご確認お願い致します

2019-03-03 07:30 UTC, ghost requested changes

2019-03-03 07:30 UTC, hiroki5123 commented on README.md
> +|update_at|datetime|null: false, foreign_key: true|
このアソシエーションは正しいですが、カラムあと２つが必要になりますので修正をお願いいたします。

2019-03-03 07:30 UTC, hiroki5123 commented on README.md
> +- has_many :groups
アソシエーションがもう１つ必要です。

2019-03-03 07:30 UTC, hiroki5123 commented on README.md
> +- has_many :users
アソシエーションがもう１つ必要です。

2019-03-03 08:30 UTC, yuki-uchida requested changes

2019-03-03 08:30 UTC, yuki-uchida commented on README.md
> +|user_id|integer|null: false, foreign_key: true|
外部キーを使用する場合にはrefferenc型で書きましょう

2019-03-03 08:30 UTC, yuki-uchida commented on README.md
> +|text|text|null: false, foreign_key: true|
groupsテーブルにtextって必要ですか？
また、foreign_keyは外部キーを参照する場合に使用します。
必要ないカラムにもforeign_keyがついてしまっているので、少し考えて見ましょう

2019-03-04 07:51 UTC, tomarumarumaru commented on README.md
> +|user_id|integer|null: false, foreign_key: true|
referencesで定義しましょう

2019-03-04 07:51 UTC, tomarumarumaru commented on README.md
> +|group_id|integer|null: false, foreign_key: true|
referencesで定義しましょう

2019-03-04 07:51 UTC, tomarumarumaru commented on README.md
> +|id|integer|null: false|
idカラムは自動生成されます
他の箇所も同様です

2019-03-04 07:51 UTC, tomarumarumaru commented on README.md
> +|user_id|integer|null: false, foreign_key: true|
user_idは中間テーブルで管理します

2019-03-04 07:51 UTC, tomarumarumaru commented on README.md
> +|update_at|datetime|null: false|
こちらも自動生成されます
他の箇所も同様です

2019-03-04 07:51 UTC, tomarumarumaru commented on README.md
> +- has_many :users
こちら修正されていません

2019-03-04 07:51 UTC, tomarumarumaru commented on README.md
> +- has_many :groups
こちら修正されていません

2019-03-04 07:51 UTC, tomarumarumaru commented on README.md
> +|name|text|null: false,|
stringで良さそうです。indexとuniqueも入れましょう

2019-03-04 07:51 UTC, tomarumarumaru commented on README.md
> +|text|text|null: false,|
contentやmessageのようなカラム名が望ましいです。画像だけでも送信できるのでnull: falseは外しましょう

2019-03-04 07:51 UTC, tomarumarumaru commented on README.md
> +|image|string|null: false,|
同様にnull: falseは外しましょう

2019-03-04 07:51 UTC, tomarumarumaru commented on README.md
> +|user_id|integer|null: false, foreign_key: true|
referencesで定義しましょう

2019-03-04 07:51 UTC, tomarumarumaru commented on README.md
> +|group_id|integer|null: false, foreign_key: true|
referencesで定義しましょう

2019-03-05 02:20 UTC, TOMARUMARU commented on README.md
> +- has_many :users, through: :groups_users
membersですかね

2019-03-05 02:20 UTC, TOMARUMARU commented on README.md
> +- has_many :groups, through: :groups_users
membersですかね

2019-03-05 02:29 UTC, TOMARUMARU commented
修正が間違っています。DB設計とアソシエーションについて調べたり復習してみてください

2019-03-05 02:46 UTC, TOMARUMARU approved these changes
LGTM

2019-03-05 02:51 UTC, merged