chatspaceビュー実装
yuto-ishida/chat-space pull request #2
Opened 2019-03-05 06:37 UTC by yuto-ishida

2019-03-05 06:43 UTC, yuto-ishida commented
ビュー実装画面です
<img width="1440" alt="2019-03-05 15 39 11" src="https://user-images.githubusercontent.com/45711511/53785892-56a9fc80-3f5d-11e9-80d2-a8479cf68dc3.png">

2019-03-05 07:12 UTC, ReoKuriyama requested changes
sidebarのcssを定義しているファイルが複数見られます
ファイルの整理をお願いします。

また、アイコンの色とデザインが異なっています。
余白も設計書とずれているように見受けられます。
修正をお願いします。

2019-03-05 07:12 UTC, ReoKuriyama commented on app/assets/stylesheets/_form.scss
> +  // height: 90px;
これはメモで置いていますか？

2019-03-05 07:12 UTC, ReoKuriyama commented on app/assets/stylesheets/_form.scss
> +
以下消しましょう

2019-03-05 07:12 UTC, ReoKuriyama commented on app/assets/stylesheets/modules/_form_scss
> +.form {
ファイル名がおかしいですね

2019-03-05 07:12 UTC, ReoKuriyama commented on app/assets/stylesheets/modules/_form.scss
> +
以下消しましょう

2019-03-05 07:15 UTC, yuto-ishida commented on app/assets/stylesheets/_form.scss
> +  // height: 90px;
メモでおいています。消した方がよいでしょうか？

2019-03-07 03:04 UTC, yuto-ishida commented
ビュー実装画面です。
<img width="1440" alt="2019-03-07 11 57 43" src="https://user-images.githubusercontent.com/45711511/53929427-123f6d80-40d1-11e9-844e-aa3dc153340c.png">

2019-03-07 03:10 UTC, TOMARUMARU commented on app/assets/stylesheets/modules/_form.scss
> +  // height: 90px;
不要なコメントアウトは消してください。

2019-03-07 03:10 UTC, TOMARUMARU commented on app/assets/stylesheets/modules/_form.scss
> +    // width: calc(100vw - 350px);
不要なコメントアウトは消してください。

2019-03-07 03:10 UTC, TOMARUMARU commented on app/views/layouts/application.html.haml
> +    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
ハッシュロケットは修正しましょう

2019-03-07 03:10 UTC, TOMARUMARU commented on app/views/layouts/application.html.haml
> +    %link{:crossorigin => "anonymous", :href => "https://use.fontawesome.com/releases/v5.7.1/css/all.css", :integrity => "sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr", :re
ハッシュロケットは修正しましょう

2019-03-07 03:10 UTC, TOMARUMARU commented on app/views/layouts/mailer.html.haml
> +!!!
mailerファイルは使用しないので削除しましょう

2019-03-07 03:10 UTC, TOMARUMARU commented on app/views/layouts/mailer.text.haml
> += yield
mailerファイルは使用しないので削除しましょう

2019-03-07 03:10 UTC, TOMARUMARU commented on config/routes.rb
> +  get 'messages' => 'messages#index'
root_pathに設定しているのでこちらは不要です

2019-03-07 05:46 UTC, hzak2xx approved these changes
LGTM

2019-03-07 06:01 UTC, merged